version: "3"

services:
  php:
    build: .
    volumes:
      - ./htdoc:/var/www/html
    depends_on:
      - mysql
    ports:
      - 8000:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
