version: "3"

services:
  php:
    image: php:7.2-apache
    volumes:
      - ./htdoc:/var/www/html
    ports:
      - 8000:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
